---

antora:
  name: modules
  dir: www
  modules:
    - name: 01-ansible-navigator-intro
      label: "Introduce the Environment"
    - name: 02-ansible-navigator-explore-ui
      label: "Exploring the Interface"
    - name: 03-configure-ansible-navigator
      label: "Configuring Options"
    - name: 04-ansible-navigator-using-execution-environments
      label: "Using Execution Environments"
    - name: 05-navigator-quiz
      label: "Knowledge Check"

tabs:
  - name: "VSCode Editor"
    url: https://vscode-${guid}.${domain}/?folder=/home/rhel/ansible-files/
    external: true
  - name: ">_ terminal"
    url: /wetty
