---
containers: []
virtualmachines:
  - name: "control"
    image: "rhel-9.5"
    memory: "4G"
    cores: 2
    image_size: "50G"
    tags:
      - key: "AnsibleGroup"
        value: "control"
      - key: "node_type"
        value: "control_node"
    networks:
      - default
