---
containers: []
virtualmachines:
  - name: "host1"
    image: "rhel-9.5"
    memory: "8G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }
      ssh_pwauth: true
      runcmd:
        - mkdir -p /home/rhel/ansible-files
        - chown rhel:rhel /home/rhel/ansible-files
        - curl -fsSL https://code-server.dev/install.sh | sh
        - mkdir -p /home/rhel/.config/code-server
        - 'echo "bind-addr: 0.0.0.0:8443" > /home/rhel/.config/code-server/config.yaml'
        - 'echo "auth: password" >> /home/rhel/.config/code-server/config.yaml'
        - 'echo "password: ansible123!" >> /home/rhel/.config/code-server/config.yaml'
        - 'echo "cert: false" >> /home/rhel/.config/code-server/config.yaml'
        - chown -R rhel:rhel /home/rhel/.config/code-server
        - systemctl enable --now code-server@rhel
